### ISSUE TITLE
board history eating up memory

### ISSUE THREAD

**Issue by mortonjack** [mortonjack/chess-OOP#31]
currently, each successful move creates a new board in memory. these really aren't needed, we only need to store 6 boards back, at most 50 for the 50-move-rule (although this could be implemented seperately). Gameboard should keep track of moveCount and once it reaches a certain number (which can be easily changed) we should delete the last board in the linked list.

**Comment by Thomas-Frew** [comment]
I agree with this. The 50-move rule can be implemented as an integer counter, which increments every move but resets when a pawn is moved, or a piece is captured.

When the counter reaches 50, the draw function is called.
