### ISSUE TITLE
Unify the inclusion of pieces?

### ISSUE THREAD

**Issue by Thomas-Frew** [mortonjack/chess-OOP#7]
Having `include/gameboard.cpp include/piece.cpp include/pawn.cpp include/knight.cpp include/bishop.cpp include/rook.cpp include/queen.cpp include/king.cpp` in each driver's Make is going to get pretty tiresome. 

Would it be worth including all of these files at once? And if so, what is the best way to do so?

**Comment by mortonjack** [comment]
https://sodocumentation.net/makefile
The Makefile can get pretty advanced & complicated. The simplest way to do this is a variable. But we could go more advanced to make more things easier.

**Comment by Thomas-Frew** [comment]
With no easy way to implement this improvement, it is better off unresolved.
