### ISSUE TITLE
Board perspective?

### ISSUE THREAD

**Issue by Thomas-Frew** [mortonjack/chess-OOP#8]
When we play chess, white usually sees the board from their perspective (ranks in ascending order) and black sees the board from their perspective (ranks in descending order). Their files are in the same order, however.

White sees:
![image](https://user-images.githubusercontent.com/109998763/190879689-7ea9abd0-0197-4e4a-8165-be8f2620d8a6.png)

Black sees:
![image](https://user-images.githubusercontent.com/109998763/190879700-8474c860-e188-4f72-a564-413101758502.png)

Would it be worth passing "colour" into visualiseTextBoard to produce these visualisations from either perspective?

**Comment by mortonjack** [comment]
https://github.com/mortonjack/chess-OOP/pull/9
check the pull request

**Comment by Thomas-Frew** [comment]
Great job! This looks amazing.
